// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nursery.Models
{
    public partial class Adz
    {
        public int AdzId { get; set; }
        public string AdzPic { get; set; }
        public int? EntityTypeId { get; set; }
        public string EntityId { get; set; }
        public bool? AdzIsActive { get; set; }
        public int? AdzOrderIndex { get; set; }
        public int CountryId { get; set; }

        public virtual Country Country { get; set; }
        public virtual EntityType EntityType { get; set; }
    }
}