// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nursery.Models
{
    public partial class Banner
    {
        public int BannerId { get; set; }
        public string BannerPic { get; set; }
        public int? EntityTypeId { get; set; }
        public string EntityId { get; set; }
        public bool? BannerIsActive { get; set; }
        public int? BannerOrderIndex { get; set; }

        public virtual EntityType EntityType { get; set; }
    }
}