// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nursery.Models
{
    public partial class Child
    {
        public int ChildId { get; set; }
        public string ChildName{ get; set; }
        public string ChildPhone { get; set; }
        public string ChildEmail { get; set; }
        public string ChildImage { get; set; }
        public int ParentId  { get; set; }
        //public DateTime BirthDate { get; set; }
        public int? NurseryMemberId { get; set; }
        public int? AgeCategoryId { get; set; }
        public virtual AgeCategory AgeCategory { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual NurseryMember NurseryMember { get; set; }

    }
}