    // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Nursery.Models
{
    public partial class Country
    {
        public Country()
        {
            City = new HashSet<City>();
    
            Adz = new HashSet<Adz>();
            Plan = new HashSet<Plan>();
            PublicDevice = new HashSet<PublicDevice>();
            PublicNotification = new HashSet<PublicNotification>();
        }

        public int CountryId { get; set; }
        public string CountryTlAr { get; set; }
        public string CountryTlEn { get; set; }
        public string CountryPic { get; set; }
        public bool? CountryIsActive { get; set; }
        public int? CountryOrderIndex { get; set; }
        [JsonIgnore]
        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<Plan> Plan    { get; set; }
        
        public virtual ICollection<Adz> Adz { get; set; }

        public virtual ICollection<PublicDevice> PublicDevice { get; set; }
        public virtual ICollection<PublicNotification> PublicNotification { get; set; }
    }
}