// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nursery.Models
{
    public partial class EntityType
    {
        public EntityType()
        {
            Adz = new HashSet<Adz>();
            Banner = new HashSet<Banner>();
        }

        public int EntityTypeId { get; set; }
        public string EntityTypeTlar { get; set; }
        public string EntityTypeTlen { get; set; }

        public virtual ICollection<Adz> Adz { get; set; }
        public virtual ICollection<Banner> Banner { get; set; }
    }
}