// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Nursery.Models
{
    public partial class NurserySubscription
    {
        public int NurserySubscriptionId { get; set; }
        public int NurseryId { get; set; }
        public int PlanId { get; set; }
        public int PlanTypeId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public double? Price { get; set; }
        public string Remarks { get; set; }
        public int? PaymentMethodId { get; set; }
        public bool IsActive { set; get; }
        public string payment_type { set; get; }
        public string PaymentID { set; get; }
        public string Result { set; get; }
        public DateTime? PostDate { set; get; }
        public string TranID { set; get; }
        public string Ref { set; get; }
        public string TrackID { set; get; }
        public string Auth { set; get; }
        [JsonIgnore]
        public virtual NurseryMember Nursery { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}