// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nursery.Models
{
    public partial class NurseryImage
    {
        public int NurseryImageId { get; set; }
        public int NurseryId { get; set; }
        public string Pic { get; set; }

        public virtual NurseryMember Nursery { get; set; }
    }
}