// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nursery.Models
{
    public partial class Plan
    {
        public Plan()
        {
            NurserySubscription = new HashSet<NurserySubscription>();
        }

        public int PlanId { get; set; }
        public string PlanTlAr { get; set; }
        public string PlanTlEn { get; set; }
        public bool? IsActive { get; set; }
        public double? Price { get; set; }
        public int? DurationInMonth { get; set; }
        public int? CountryId { get; set; }
        public virtual Country Country { get; set; }
        //public int? PhaseId { get; set; }
        //public virtual Phase Phase { get; set; }

        public virtual ICollection<NurserySubscription> NurserySubscription { get; set; }
    }
}