// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nursery.Models
{
    public partial class SystemConfiguration
    {
        public int Id { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string Address { get; set; }
        public string Logo { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string About { get; set; }
        public string Terms { get; set; }
        public string Policy { get; set; }
    }
}